Bring back ThemeUtils for Theming
Squahed with:

    Author: Pranav Vashi <neobuddy89@gmail.com>
    Date:   Sat Feb 19 18:44:31 2022 +0530

    ThemeUtils: Make it compatible for all targets

    * Also, sort packages here itself and remove unused function.

    Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>
    Change-Id: Id2b8e924094d2187ded969e396939256ffda9fb4

    Author: spezi77 <spezi7713@gmx.net>
    Date:   Tue Dec 14 17:18:13 2021 +0100

    ThemeOverlayApplier: Catch a potential NPE

    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.om.OverlayIdentifier android.content.om.FabricatedOverlay.getIdentifier()' on a null object reference

    Signed-off-by: spezi77 <spezi7713@gmx.net>

    Author: Pranav Vashi <neobuddy89@gmail.com>
    Date:   Sat Aug 24 02:07:37 2024 +0530

    ThemeUtils: Use current user for THEME_CUSTOMIZATION_OVERLAY_PACKAGES

    * Follow ThemePicker and SystemUI.

    Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>

Co-authored-by: Pranav Vashi <neobuddy89@gmail.com>
Co-authored-by: spezi77 <spezi7713@gmx.net>
Change-Id: I4324e8bc8d7c6d7df1809a1bd3424abf4dfa1306